[[Clang]]
arch = "aarch64"
git-tree-sha1 = "bb2ae850464795777f36202dd7e790b0db2f2064"
os = "macos"

    [[Clang.download]]
    sha256 = "79ba9d19184c3df76694523d8a49acdc53a5ba88c30cc966537de5258b950eaf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "600b2be6dbe19d9125a349193eb1b3eb184301a6"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5d8ed74cc6032213cc497e33fd57b8c0d26386f302ec972d9ac35215e0f710d0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "023c477862419fdef42e887d7d3196a78f22182e"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f525bb1075cd8f4a4598990cc4de352ec10ba828ae0f718c8da0abca2e90a782"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0da9b1ef6db5b4636b6424fe5dd503d06fadc90"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9ea7e0e3a24ac8662df42b12d6f9496a8bbc2cb0608e78c274398902394b3858"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39a1f03ed2946aed1ee21976409eb0f641853124"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5dad74eb5b64c311ac5aad64435d1e67faa2884b731b876dd5cc988067174ded"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "787f6409d137cece84752253f1d6281364b90b55"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "def378700b521c23693585ee4662685c0725daa445359a0e14188be77666516d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4805cfb7dc5f269e1cf53ee05f72367f30069e3"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "74550c3dce03719f663bcd8080fe0ffce821ce822dcbc61b233d474c6bc19e69"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb09029b4d8e4ee6995387cb7961cf03a19c1129"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "0e5e1f27686f7cb0fa1caa51e3d389aed5d9c28b6f12e09fd29dab551a0ff09e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f50bdb8386a0db6e59b30047fdcdefbea7f95425"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "90204c6578ad731228d9b4a308399395ae19f06983fa1cee03d277360bcd0529"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc039852906206c2c65fddcc14bf4b0327428793"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3c8a6d141a1d929771c07f6c06a0a1ed5275dc39564e8b93eb54c2875fe13d0d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2104f66b3a9f8a5ff7db59cb6073b3d939b444fe"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5f74c6d9c029dc6ae6db0d3b1a28cd6cb7d159c2cb1c70d00e1e5ffe3703ab22"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4135c1c5de976f14c5d9cae8660d2039a8cf3541"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "58d774e3923ceab0d1e76be2112c0e5a75777962cd87773158db4c48d6c99d6f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3159e79c97760ce5fdf36f07174121c1f7b637ff"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "e660459c74345d8e4abb14b3c6482aa233134af5e9176de9c2813cd6e829f0d2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d4fdbccdd99c30317001b4c47f6c9c3cf131586"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e018f5f9d39d52d6c1b608fd68b08d680429af77f84db2e33a8b916523724fda"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76899a5cf69771f5ad30c7664946dcf4ea554aaf"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8e56a1d32ee315de5871335a95deb76467f76c240e09cbf476c9746eb4eb6de7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27f7fd70431f79f856151c05f1b6b6a1b0f86a0c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "eb090a5841976a9217f38fc35b706ddb377a8dbb24b8929a306dd8be7f5bfc5f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e0bb943189ebf72dac03875a210eca77b1770ec"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "ae09a1af8b29950601f7e66c60bbf79d831eeffc4770a9eb814c14fff0e7391b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f618f39e6111d53fe7b85eaa41a71d2df25946bb"
os = "windows"

    [[Clang.download]]
    sha256 = "47765115f2e56818495c4be485763d60235b43e71d88ca036323afdc558ed099"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "178c054dde27bc155f565784ca4ff37d12e14f02"
os = "windows"

    [[Clang.download]]
    sha256 = "b9d9b54f29cd50ab7fc52391f91912fc0a587f222b11500af80d0590c614e2ec"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5223e945cea1acf41704b30c20553d6d4380d6c6"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "fa6e1d75b72927827200d196be5555153deb04167b637faa4abeaca059edb63b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c300e41055022553ad4b9a87659bad135f987a4d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a89121ff0831c9099df1f071bd91e784d3a43fa70b9cadb12edc323d092a55ec"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "807a78ae469baf39a933c1cdabc3513076bafa7d"
os = "macos"

    [[Clang.download]]
    sha256 = "506eb7cbb187af476904d108852098ad317fc62e7a26be697c34773e171a986d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9dc149f9a31f5e7b6068a6a8f377683c61ded52e"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "46148ea45a37f5e5de8772d8ffd5409caa592a85c3658f84fa9e65556634a753"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebac8bb0527804a315b230ade306d81c03684e58"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "218acd9899502c24f39dbda3a0669b7af299dcb6f93e5818ce8a52bad9c4135c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbeb26610916885ec4e2a595f650e25d09c3e1cc"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "789349647704cc3a321dfbc3478adc2c075f7195c716f9352db4df242fee6c43"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64db1ea538c633a39f04918fafaff418d5863508"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "81c01bf02247e5bf959f5c8dfb00b9749d7955c7a1c3580e3dc99650d030e15d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "5d0c9df608fddb6cfde3291718af7916c0282363"
os = "freebsd"

    [[Clang.download]]
    sha256 = "a94db842b51a20b63f9e8a2ece256c67c5c3b39dcd88f6d25a3c701ed70ef077"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3808c4a1dc49c8758a1ba48e34ce6665c46639d"
os = "windows"

    [[Clang.download]]
    sha256 = "6e41393584b2d97beacdea67e2f2ce247ff44f9e6363150781af492be2ee2f3c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d00503bfe0c9590155cd8f1326fcb33ba5799f3a"
os = "windows"

    [[Clang.download]]
    sha256 = "64821adbf642328d2e1bb544fc82747544964602d1dbdea6ea35de3e54002045"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+3/Clang.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
